### PR TITLE
Downgrade nbconvert

### PR DESCRIPTION
**Pull request by jasonyzhang**
nbconvert>=5 ignores latex compilation errors and just compiles the pdf up until the error. This is a problem for students who don't realize that their assignment output is incomplete.

Let me know when it gets added to staging for testing!

### CODE REVIEW

**Comment by jasonyzhang** [comment]
Yeah, I actually brought notebook's version back up to 5.6

**Comment by ryanlovett** [comment]
I see it, thanks! When you get the chance can you please file a new issue with nbconvert?

**Comment by jasonyzhang** [comment]
Looks like nbconvert<5 doesn't work with notebook==5.6.0. I'm getting 500 Internal Server Error.
Could you revert?

**Comment by ryanlovett** [comment]
Done.
